volumes:
    postgres-data:
        external: true
services:
    react:
      image: node:lts-bullseye
      command: /bin/bash run.sh
      working_dir: /app
      volumes:
        - ./ghi/app:/app
      ports:
        - "3000:3000"
      environment:
        HOST_OS: ${OS}
        NODE_ENV: development
        HOST: "0.0.0.0"
    database:
      image: postgres:14.2-bullseye
      volumes:
        - postgres-data:/var/lib/postgresql/data
        - ./db:/docker-entrypoint-initdb.d
      environment:
          - POSTGRES_MULTIPLE_DATABASES=concerts,buddy,ticket
          - POSTGRES_PASSWORD=test-databases
      ports:
          - 15432:5432
    concerts-api:
      build:
        context: ./concerts-api
        dockerfile: ./Dockerfile.dev
      ports:
        - "8100:8000"
      volumes:
        - ./concerts-api:/app
      depends_on:
        - database
      environment:
        DATABASE_URL: postgres://concerts:password@database:5432/concerts
        WAIT_HOSTS: database:5432
        WAIT_TIMEOUT: 240
    buddy-api:
      build:
        context: ./buddy-api
        dockerfile: ./Dockerfile.dev
      ports:
        - "8080:8000"
      volumes:
        - ./buddy-api:/app
      depends_on:
        - database
      environment:
        DATABASE_URL: postgres://buddy:password@database:5432/buddy
        WAIT_HOSTS: database:5432
        WAIT_TIMEOUT: 240
    ticket-api:
      build:
        context: ./ticket-api/
        dockerfile: ./Dockerfile.dev
      ports:
        - "8090:8000"
      volumes:
        - ./ticket-api:/app
      depends_on:
        - database
      environment:
        DATABASE_URL: postgres://ticket:password@database:5432/ticket
        WAIT_HOSTS: database:5432
        WAIT_TIMEOUT: 240
    tickets-poller:
      build:
        context: ./ticket-api/poll
        dockerfile: ./Dockerfile.dev
      volumes:
        - ./ticket-api/poll:/app
        - ./ticket-api/ticket_project:/app/ticket_project
        - ./ticket-api/ticket_rest:/app/ticket_rest
      depends_on:
        - database
        - ticket-api
      environment:
        DATABASE_URL: postgres://ticket:password@database:5432/ticket
        WAIT_HOSTS: database:5432,ticket-api:8000
        WAIT_TIMEOUT: 240
    tickets-user-poller:
      build:
        context: ./ticket-api/userpoll
        dockerfile: ./Dockerfile.dev
      volumes:
        - ./ticket-api/userpoll:/app
        - ./ticket-api/ticket_project:/app/ticket_project
        - ./ticket-api/ticket_rest:/app/ticket_rest
      depends_on:
        - database
        - ticket-api
      environment:
        DATABASE_URL: postgres://ticket:password@database:5432/ticket
        WAIT_HOSTS: database:5432,ticket-api:8000
        WAIT_TIMEOUT: 240
