# Generated by Django 4.0.3 on 2022-07-12 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('venue', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('artist', models.CharField(max_length=100)),
                ('concert_id', models.CharField(max_length=100)),
                ('venue_id', models.CharField(max_length=100)),
                ('artist_id', models.CharField(max_length=100)),
            ],
        ),
    ]
