# Generated by Django 4.0.3 on 2022-07-13 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
