# Generated by Django 4.0.3 on 2022-07-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts_rest', '0005_alter_concert_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
