# Generated by Django 4.0.3 on 2022-07-14 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts_rest', '0006_alter_concert_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='concert_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
