# Generated by Django 4.0.3 on 2022-07-15 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concerts_rest', '0007_alter_concert_concert_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concert',
            name='name',
        ),
    ]
