# Generated by Django 4.0.3 on 2022-07-13 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConcertVO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_href', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('venue', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('artist', models.CharField(max_length=100)),
                ('concert_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserVO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_href', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('section', models.CharField(max_length=20)),
                ('row', models.CharField(max_length=20)),
                ('seat', models.CharField(max_length=20)),
                ('sold', models.BooleanField(default=False)),
                ('picture_url', models.URLField()),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buyer_tickets', to='ticket_rest.uservo')),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='concert_tickets', to='ticket_rest.concertvo')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seller_tickets', to='ticket_rest.uservo')),
            ],
        ),
    ]
