# Generated by Django 4.0.3 on 2022-07-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concertvo',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
