# Generated by Django 4.0.3 on 2022-07-21 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buddy_rest", "0009_concert_fellow_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="concert",
            field=models.ManyToManyField(null=True, to="buddy_rest.concert"),
        ),
    ]
