FROM python:3.10-bullseye
RUN python -m pip install --upgrade pip
WORKDIR /app

COPY requirements.txt requirements.txt
COPY ticket_project ticket_project
COPY common common
COPY ticket_rest ticket_rest
COPY poll/poller.py poller.py

RUN pip install -r requirements.txt
CMD python poller.py
